### ISSUE TITLE
docker-compose upしてもnode_modules errorになって起動しない

### ISSUE THREAD

**Issue by takumi12311123** [takumi12311123/for-spring-training#34]
![image_720](https://user-images.githubusercontent.com/103009749/222881772-066d180c-d9c6-44a5-815e-396d8caaf5a1.png)

このエラーから消えない

やったこと
・package.json書き直して、docker-compose up
・docker container 消して、docker-compose up

してもダメ

次は
・image と container消して、docker-compose up
・node_modules消して、npm i
@MomokaUsui  の解決法を聞いて試してもらう

どっちかで解決できなかったら、お蔵入り

**Comment by takumi12311123** [comment]
今、対象者がバイトなうなので、早めに解決してあげたい

**Comment by takumi12311123** [comment]
一回、imageとcontainer削除を提案してみるのがいい気がしてきた

**Comment by takumi12311123** [comment]
1.コンテナとイメージ削除

むりなら

2.ファイルも全部削除

むりなら

3.node 全削除、npm i 

で

**Comment by yoshiki495** [comment]
対象の images 削除 > docker compose up で解決
