### ISSUE TITLE
PostgreSQLに接続出来ない

### ISSUE THREAD

**Issue by yoshiki495** [takumi12311123/for-spring-training#35]
![IMG_3673](https://user-images.githubusercontent.com/68012132/222944743-8b63e4b3-876d-4df1-a42e-432518227c24.jpg)

**Comment by yoshiki495** [comment]
PostgreSQLコンテナ再起動で解決（PosgreSQLの設定がうまくできなかったっぽい）

**Comment by takumi12311123** [comment]
困った時はコンテナ再起動を声を大きくして言いたい
